-- ALL.sql — every numbered migration in this directory, in order.
-- GENERATED by scripts/check-migrations.js --write. Do not edit by hand:
-- change the numbered file and regenerate. tests/migrations.test.js fails
-- when this file drifts from the numbered files.
--
-- For a fresh Supabase project: SQL Editor → paste → run. For an existing
-- database apply only the numbered files it has not had yet (see
-- docs/RELEASE-*.md).

-- ─────────────────────────────────────────────────────────────
-- 001_initial_schema.sql
-- ─────────────────────────────────────────────────────────────
-- YAHEALTHY — סכימה ראשונית
-- נגזרה מהקוד: utils/database.js (הטבלאות והשאילתות) ו-index.js (שדות ה-payload).
-- ADR-001 קבע Supabase. זו המיגרציה הראשונה בפרויקט.
--
-- הרצה: Supabase Dashboard → SQL Editor → הדבק והרץ.
-- בטוח להרצה חוזרת: הכל IF NOT EXISTS.

-- ─────────────────────────────────────────────────────────────
-- users
-- ─────────────────────────────────────────────────────────────
create table if not exists public.users (
  id            uuid primary key,
  email         text not null,
  password_hash text not null,
  name          text,
  preferences   jsonb,
  created_at    timestamptz not null default now()
);

-- האפליקציה מחפשת לפי אימייל מנורמל לאותיות קטנות. אילוץ ייחודיות
-- על ביטוי lower() מונע שני חשבונות שנבדלים רק באותיות גדולות.
create unique index if not exists users_email_lower_key
  on public.users (lower(email));

-- ─────────────────────────────────────────────────────────────
-- surveys — שאלון בריאות. 🩺 מידע רגיש.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.surveys (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.users(id) on delete cascade,
  gender              text,
  height_cm           numeric,
  weight_kg           numeric,
  target_weight_kg    numeric,
  target_days         integer,
  lifestyle           text,
  bmi                 numeric,
  body_fat_percent    numeric,
  bmr                 numeric,
  tdee                numeric,
  daily_calories      jsonb,
  water_target_liters numeric,
  sleep_target_hours  numeric,
  protein_target_g    numeric,
  created_at          timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- weight_goals / weight_logs — 🩺 מידע רגיש.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.weight_goals (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references public.users(id) on delete cascade,
  start_weight_kg  numeric,
  target_weight_kg numeric,
  weigh_in_days    jsonb,
  created_at       timestamptz not null default now()
);

create table if not exists public.weight_logs (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.users(id) on delete cascade,
  goal_id      uuid references public.weight_goals(id) on delete set null,
  weight_kg    numeric,
  water_liters numeric,
  sleep_hours  numeric,
  celebration  text,
  created_at   timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- הרגלים יומיים
-- ─────────────────────────────────────────────────────────────
create table if not exists public.hydration_logs (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.users(id) on delete cascade,
  date            date,
  liters_consumed numeric,
  time_of_day     text,
  created_at      timestamptz not null default now()
);

create table if not exists public.sleep_logs (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.users(id) on delete cascade,
  date          date,
  sleep_hours   numeric,
  sleep_quality text,
  created_at    timestamptz not null default now()
);

create table if not exists public.fasting_windows (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.users(id) on delete cascade,
  window_hours numeric,
  protocol     text,
  created_at   timestamptz not null default now()
);

create table if not exists public.readiness_scores (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.users(id) on delete cascade,
  hrv         numeric,
  resting_hr  numeric,
  sleep_hours numeric,
  score       numeric,
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- meal_swaps — allergies מגיע מהמשתמש. 🩺 רגיש.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.meal_swaps (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.users(id) on delete cascade,
  ingredients jsonb,
  allergies   jsonb,
  swaps       jsonb,
  created_at  timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- offline_logs — סנכרון מהלקוח. log_type/data הם payload שרירותי.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.offline_logs (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.users(id) on delete cascade,
  log_type   text,
  data       jsonb,
  synced     boolean not null default false,
  created_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- food_logs — ליבת המוצר. 15 endpoints נשענים עליה.
-- ─────────────────────────────────────────────────────────────
create table if not exists public.food_logs (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.users(id) on delete cascade,
  date          date,
  name          text,
  meal_type     text,
  calories      numeric,
  protein_grams numeric,
  carbs_grams   numeric,
  fat_grams     numeric,
  notes         text,
  created_at    timestamptz not null default now()
);

create table if not exists public.food_log_templates (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.users(id) on delete cascade,
  name          text,
  meal_type     text,
  calories      numeric,
  protein_grams numeric,
  carbs_grams   numeric,
  fat_grams     numeric,
  notes         text,
  created_at    timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────
-- אינדקסים — לפי מה שהקוד באמת מסנן וממיין
-- (utils/database.js: eq על user_id/date/goal_id/synced,
--  order על created_at/date, טווחים על date)
-- ─────────────────────────────────────────────────────────────
create index if not exists food_logs_user_date_idx        on public.food_logs (user_id, date desc);
create index if not exists food_logs_user_created_idx     on public.food_logs (user_id, created_at desc);
create index if not exists food_log_templates_user_idx    on public.food_log_templates (user_id, created_at desc);
create index if not exists surveys_user_idx               on public.surveys (user_id, created_at desc);
create index if not exists weight_goals_user_idx          on public.weight_goals (user_id, created_at desc);
create index if not exists weight_logs_user_idx           on public.weight_logs (user_id, created_at desc);
create index if not exists weight_logs_goal_idx           on public.weight_logs (goal_id);
create index if not exists hydration_logs_user_date_idx   on public.hydration_logs (user_id, date desc);
create index if not exists sleep_logs_user_date_idx       on public.sleep_logs (user_id, date desc);
create index if not exists fasting_windows_user_idx       on public.fasting_windows (user_id, created_at desc);
create index if not exists readiness_scores_user_idx      on public.readiness_scores (user_id, created_at desc);
create index if not exists meal_swaps_user_idx            on public.meal_swaps (user_id, created_at desc);
create index if not exists offline_logs_user_synced_idx   on public.offline_logs (user_id, synced);

-- ─────────────────────────────────────────────────────────────
-- 🔴 RLS — הגנה בעומק
--
-- השרת ניגש עם מפתח secret ולכן עוקף RLS ממילא. ההפעלה כאן היא
-- רשת ביטחון: אם מפתח ציבורי ידלוף או ייחשף מהלקוח, הוא לא יוכל
-- לקרוא שורה אחת. בלי זה, מפתח שדלף = כל נתוני הבריאות חשופים.
--
-- אין policies בכוונה: ברירת המחדל היא דחייה מוחלטת לכל מי שאינו
-- service/secret. כשה-frontend יקרא ישירות ל-Supabase — מוסיפים
-- policies לפי auth.uid(), לא לפני.
-- ─────────────────────────────────────────────────────────────
alter table public.users              enable row level security;
alter table public.surveys            enable row level security;
alter table public.weight_goals       enable row level security;
alter table public.weight_logs        enable row level security;
alter table public.hydration_logs     enable row level security;
alter table public.sleep_logs         enable row level security;
alter table public.fasting_windows    enable row level security;
alter table public.readiness_scores   enable row level security;
alter table public.meal_swaps         enable row level security;
alter table public.offline_logs       enable row level security;
alter table public.food_logs          enable row level security;
alter table public.food_log_templates enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 001_whapi_bot_conversations.sql
-- ─────────────────────────────────────────────────────────────
-- First migration in this repo (ADR-002 follow-up, decisions.md step 4).
-- Run in the Supabase SQL editor before the WHAPI webhook goes live.
--
-- Rollback:
--   drop table if exists whapi_messages;
--   drop table if exists whapi_conversations;

create table if not exists whapi_conversations (
  phone text primary key,
  active_bot text not null default 'nuri' check (active_bot in ('nuri', 'chef')),
  updated_at timestamptz not null default now()
);

create table if not exists whapi_messages (
  id bigint generated always as identity primary key,
  phone text not null references whapi_conversations(phone) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

-- Covers both the FK lookup and the actual query pattern (recent messages per phone).
create index if not exists whapi_messages_phone_created_idx
  on whapi_messages (phone, created_at);

-- These tables are written only by the backend server, never read directly by a
-- client. RLS is enabled with no policies, so the anon/authenticated roles get
-- zero access by default; only the Postgres service_role (which bypasses RLS)
-- can read or write them.
--
-- The rest of this app's tables connect via SUPABASE_KEY, documented in
-- .env.example as the anon key. If that is what's actually configured, the
-- webhook's DB calls will fail against these two tables until the backend
-- also has a service-role key. Add SUPABASE_SERVICE_ROLE_KEY (Supabase
-- dashboard -> Settings -> API) and use it for the four whapi* functions in
-- utils/database.js -- see the comment there.
alter table whapi_conversations enable row level security;
alter table whapi_messages enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 002_whatsapp_messages.sql
-- ─────────────────────────────────────────────────────────────
-- WhatsApp — הודעות נכנסות מ-WHAPI
-- נגזר מצורת ה-webhook האמיתית שנצפתה ב-20/09/2026.
-- נתיב חזרה: drop table public.whatsapp_messages;

create table if not exists public.whatsapp_messages (
  -- המזהה של WHAPI. משמש כמפתח ראשי כדי שמסירה כפולה של אותו
  -- webhook לא תיצור שתי שורות — WHAPI שולח שוב על כישלון.
  id          text primary key,
  chat_id     text not null,
  from_number text,
  from_name   text,
  from_me     boolean not null default false,
  type        text,
  body        text,
  sent_at     timestamptz,

  -- מצב הטיפול. אין כאן תשובה אוטומטית: הודעה נכנסת ומחכה.
  --   pending   — התקבלה, לא טופלה
  --   drafted   — נוסחה תשובה וממתינה לאישור
  --   answered  — נשלחה תשובה
  --   escalated — 🩺 דגל בריאותי, עוברת לאדם ולא נענית אוטומטית
  status      text not null default 'pending',

  -- ה-payload המלא כפי שהתקבל. נשמר כדי שנוכל להבין מבנה שלא צפינו
  -- בלי לאבד את ההודעה.
  raw         jsonb,
  received_at timestamptz not null default now()
);

create index if not exists whatsapp_messages_status_idx
  on public.whatsapp_messages (status, received_at desc);
create index if not exists whatsapp_messages_chat_idx
  on public.whatsapp_messages (chat_id, sent_at desc);

-- 🔴 הודעות מלקוחות עלולות להכיל מידע בריאותי — מישהו כותב "אני בהריון"
-- לפני שיש לו חשבון. RLS מופעל, בלי policies, כמו שאר הטבלאות.
alter table public.whatsapp_messages enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 003_rename_nuri_to_adi.sql
-- ─────────────────────────────────────────────────────────────
-- Renames the internal bot identifier from 'nuri' to 'adi'.
--
-- Persona history: Nuri -> Mor -> Adi. The first two renames only ever
-- touched user-facing prose (docs/bot/nuri-bot-prompt.md, routes/whapi.js
-- strings) -- migrations/001 hardcoded the original name as stored data
-- (the default and the check constraint below), and that survived both
-- renames until now.
--
-- No longer a hard prerequisite for deploying the code that writes 'adi' as
-- active_bot: utils/database.js (getWhapiConversation/upsertWhapiConversation)
-- now normalizes at the boundary -- a write of 'adi' that hits this
-- constraint before it's been updated retries once with the legacy 'nuri'
-- value instead of failing, and a row read back as 'nuri' is returned as
-- 'adi' -- so an existing conversation never loses its system prompt
-- (SYSTEM_PROMPTS keyed by 'adi', not 'nuri') either way. Run this whenever
-- convenient regardless: it's the real fix (the stored data matches the
-- code's vocabulary, so anyone reading the table directly -- e.g. in the
-- Supabase dashboard -- isn't confused by a stale 'nuri'), the fallback in
-- database.js is a safety net, not a replacement for it. Once this has run,
-- that fallback path simply never triggers again.
--
-- Rollback:
--   alter table whapi_conversations drop constraint if exists whapi_conversations_active_bot_check;
--   update whapi_conversations set active_bot = 'nuri' where active_bot = 'adi';
--   alter table whapi_conversations alter column active_bot set default 'nuri';
--   alter table whapi_conversations add constraint whapi_conversations_active_bot_check check (active_bot in ('nuri', 'chef'));

begin;

alter table whapi_conversations drop constraint if exists whapi_conversations_active_bot_check;

update whapi_conversations set active_bot = 'adi' where active_bot = 'nuri';

alter table whapi_conversations alter column active_bot set default 'adi';

alter table whapi_conversations
  add constraint whapi_conversations_active_bot_check check (active_bot in ('adi', 'chef'));

commit;

-- ─────────────────────────────────────────────────────────────
-- 003_token_version.sql
-- ─────────────────────────────────────────────────────────────
-- token_version — הופך טוקן חתום לטוקן שאפשר לבטל.
--
-- עד כאן JWT היה תקף 7 ימים ואי אפשר היה לעצור אותו: "התנתקות" מחקה
-- אותו מהדפדפן בלבד, ואיפוס סיסמה לא ניתק את מי שכבר היה בפנים.
-- המספר הזה נחתם בתוך הטוקן ונבדק מול השורה בכל בקשה. העלאה שלו
-- באחד מהמצבים הבאים פוסלת מיידית כל טוקן שהונפק קודם:
--   התנתקות · שינוי סיסמה · איפוס סיסמה
--
-- היא גם מה שהופך טוקן איפוס לחד-פעמי: הוא נושא את הערך שהיה בשעת
-- ההנפקה, והאיפוס עצמו מעלה אותו — כך שאותו טוקן לא יעבוד פעמיים.
--
-- נתיב חזרה: alter table public.users drop column token_version;

alter table public.users
  add column if not exists token_version integer not null default 0;

-- ─────────────────────────────────────────────────────────────
-- 004_meal_plans.sql
-- ─────────────────────────────────────────────────────────────
-- meal_plans — התוכנית השבועית שהלקוח משלם עליה.
--
-- עד כאן היא ישבה ב-`const mealPlans = []` בתוך index.js. כלומר: כל restart
-- של השרת מחק לכל הלקוחות את התוכנית ואת רשימת הקניות שנגזרת ממנה, בלי
-- שגיאה ובלי דרך לשחזר. אי אפשר לגבות כסף על מוצר שלא שורד אתחול.
--
-- rows נמחקות יחד עם המשתמש, כמו כל שאר הטבלאות.
--
-- נתיב חזרה: drop table public.meal_plans;

create table if not exists public.meal_plans (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.users(id) on delete cascade,

  -- מזהה מתוך data/recipes.json ("recipe_12"), לא מפתח זר: המתכונים הם
  -- קובץ תוכן ולא טבלה. אם הם יעברו ל-DB, זה הופך ל-references.
  recipe_id  text not null,

  date       date not null,
  meal_type  text not null,
  completed  boolean not null default false,
  created_at timestamptz not null default now(),

  -- ארוחה אחת לכל סוג ביום. הקוד כבר התנהג כך כשייצר תוכניות אוטומטית,
  -- אבל שום דבר לא אכף את זה — ויצירה ידנית יכלה לשתול כפילויות שרשימת
  -- הקניות הייתה סופרת פעמיים.
  unique (user_id, date, meal_type)
);

create index if not exists meal_plans_user_date_idx
  on public.meal_plans (user_id, date);

-- 🔴 תוכנית תזונה אישית היא מידע בריאותי. RLS מופעל, בלי policies,
-- כמו שאר הטבלאות — ה-backend הוא השוער.
alter table public.meal_plans enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 004_nutrition_engine_storage.sql
-- ─────────────────────────────────────────────────────────────
-- Phase 1 storage for the deterministic nutrition engine
-- (utils/nutrition-calculator.js, utils/food-calculator.js): a person's
-- profile (what the calculator needs -- age/sex/height/weight/goal/activity)
-- and their daily food log ("ledger" -- what they've actually logged eating,
-- with calories/macros already computed by the engine, never by the model).
--
-- Not yet read or written by any live code path. This is the storage side
-- of the engine being built before it's wired into the conversation --
-- routes/whapi.js and docs/bot/nuri-bot-prompt.md still hold the current
-- customer-facing boundary (general structure, no exact numbers) until
-- that wiring is a deliberate, separately-tested step.
--
-- Rollback:
--   drop table if exists food_log_entries;
--   drop table if exists user_nutrition_profile;

create table if not exists user_nutrition_profile (
  phone text primary key references whapi_conversations(phone) on delete cascade,
  age int check (age between 10 and 120),
  sex text check (sex in ('male', 'female')),
  height_cm numeric check (height_cm between 50 and 250),
  weight_kg numeric check (weight_kg between 20 and 400),
  goal text check (goal in ('lose', 'gain', 'maintain')),
  activity_level text check (activity_level in ('sedentary', 'light', 'moderate', 'active', 'very_active')),
  updated_at timestamptz not null default now()
);

create table if not exists food_log_entries (
  id bigint generated always as identity primary key,
  phone text not null references whapi_conversations(phone) on delete cascade,
  logged_at timestamptz not null default now(),
  description text not null,
  calories numeric not null,
  protein_g numeric not null,
  carbs_g numeric not null,
  fat_g numeric not null
);

-- Covers both the FK lookup and the actual query pattern (today's entries /
-- running total per phone), same reasoning as whapi_messages_phone_created_idx
-- in migrations/001.
create index if not exists food_log_entries_phone_logged_idx
  on food_log_entries (phone, logged_at);

-- Same posture as whapi_conversations/whapi_messages (migrations/001): written
-- only by the backend server via the service-role key, never read directly by
-- a client. RLS on with no policies means anon/authenticated get zero access.
alter table user_nutrition_profile enable row level security;
alter table food_log_entries enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 005_subscriptions_and_payments.sql
-- ─────────────────────────────────────────────────────────────
-- מנויים ואירועי תשלום — ADR-007.
--
-- שתי טבלאות, שני תפקידים נפרדים:
--   subscriptions  — מה הלקוח קנה ועד מתי. זה מה שקובע הרשאה.
--   payment_events — מה PayPlus הודיע לנו. זה מה שמונע חיוב כפול.
--
-- ההפרדה חשובה: ספק הסליקה שולח את אותה הודעה יותר מפעם אחת, וטבלת
-- האירועים היא מה שהופך מסירה חוזרת לחסרת השפעה.
--
-- נתיב חזרה: drop table public.payment_events; drop table public.subscriptions;

create table if not exists public.subscriptions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.users(id) on delete cascade,

  -- 'base' — מסלול בסיס · 'yoni' — מסלול עם יוני (ADR-007, אוחד ב-009)
  plan       text not null,

  -- 'active' · 'cancelled' · 'expired'
  status     text not null default 'active',

  started_at timestamptz not null default now(),

  -- null = ללא תאריך סיום. מי שמבטל לפי זכות הביטול מקבל כאן תאריך,
  -- והשורה נשמרת — ההיסטוריה היא מה שמוכיח מה נמכר ומתי.
  ends_at    timestamptz,
  created_at timestamptz not null default now()
);

-- מנוי פעיל אחד לכל מסלול. שני מנויים פעילים לאותו אדם לאותו מסלול
-- הם תמיד תקלה — בדרך כלל מסירה כפולה של webhook.
create unique index if not exists subscriptions_one_active_per_plan
  on public.subscriptions (user_id, plan)
  where status = 'active';

create index if not exists subscriptions_user_idx
  on public.subscriptions (user_id, status);

create table if not exists public.payment_events (
  -- המזהה של PayPlus לבקשת התשלום. מפתח ראשי בכוונה: מסירה חוזרת של
  -- אותו callback נופלת על אילוץ ייחודיות במקום להיבדק ב-if שתי בקשות
  -- מקבילות יכולות לחמוק ממנו.
  page_request_uid text primary key,

  user_id     uuid references public.users(id) on delete set null,
  email       text,
  plan        text,
  status      text not null,
  amount      numeric,
  currency    text,

  -- ה-payload כפי שהתקבל, אחרי אימות חתימה. נשמר כדי שנוכל להסביר
  -- חיוב שנוי במחלוקת בלי להסתמך על הזיכרון של מישהו.
  raw         jsonb,
  received_at timestamptz not null default now()
);

create index if not exists payment_events_email_idx
  on public.payment_events (email, received_at desc);

-- 🔴 מי קנה מה הוא מידע אישי. RLS מופעל, בלי policies, כמו שאר הטבלאות.
alter table public.subscriptions  enable row level security;
alter table public.payment_events enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 006_chef_requests.sql
-- ─────────────────────────────────────────────────────────────
-- chef_requests — "נדאג שהשף יצור איתך קשר" כמצב בדאטה, לא כמשפט.
--
-- ADR-007: השף הוא אדם. הבטחה שנאמרת ללקוח ולא נרשמת בשום מקום היא
-- הבטחה שתישבר — אף אחד לא יודע שמישהו מחכה.
--
-- נתיב חזרה: drop table public.chef_requests;

create table if not exists public.chef_requests (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.users(id) on delete cascade,

  -- 'open' — ממתין · 'contacted' — השף יצר קשר · 'closed' — טופל
  status       text not null default 'open',

  -- מה הלקוח כתב, אם כתב. 🩺 לא לשים כאן ייעוץ תזונתי — השף מלמד לבשל.
  note         text,

  requested_at timestamptz not null default now(),
  contacted_at timestamptz
);

-- בקשה פתוחה אחת ללקוח. לחיצה כפולה לא יוצרת שתי בקשות ולא שתי שיחות.
create unique index if not exists chef_requests_one_open_per_user
  on public.chef_requests (user_id)
  where status = 'open';

create index if not exists chef_requests_status_idx
  on public.chef_requests (status, requested_at desc);

alter table public.chef_requests enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 007_foods.sql
-- ─────────────────────────────────────────────────────────────
-- foods — ערכים תזונתיים לכל 100 גרם, עם מקור לכל שורה.
--
-- שתי הכרעות שמעצבות את הטבלה:
--
-- 1. **הכול ל-100 גרם.** "תפוח" הוא לא כמות. תפוח קטן ותפוח גדול הם אותו
--    מזון במשקל שונה, וכל חישוב לכמות נגזר מהבסיס הזה.
--
-- 2. **אין שורה בלי מקור.** `source` ו-`source_ref` הם NOT NULL בכוונה:
--    ערך קלורי שאי אפשר להצביע על מקורו הוא ערך שהיועצת לא יכולה להגן
--    עליו מול לקוחה. שורה בלי מקור פשוט לא נכנסת.
--
-- נתיב חזרה: drop table public.foods;

create table if not exists public.foods (
  id            uuid primary key default gen_random_uuid(),

  name_he       text not null,
  name_en       text,

  -- ירקות · פירות · חלב · ביצים · בשר · דגים · קטניות · דגנים · שומן · אחר
  category      text,

  -- נא · מבושל · אפוי · מטוגן · יבש · משומר.
  -- עדשים יבשות ועדשים מבושלות אינן אותו מזון: ספיחת מים משנה את הערך
  -- ל-100 גרם פי שלושה. בלי השדה הזה המאגר משקר בלי לשים לב.
  state         text not null default raw,

  -- כמה גרם יש ביחידה אחת נפוצה - ביצה אחת, כף שמן, פרוסת לחם.
  -- null = לא ידוע, ואז לא ממירים יחידות לגרמים ולא מנחשים.
  grams_per_unit numeric,
  unit_he        text,

  -- ⚠️ הליבה. תמיד ל-100 גרם, תמיד קילו-קלוריות.
  -- FDC מחזיר לחלק מהרשומות קילו-ג'ול; ההמרה נעשית בטעינה, לא כאן.
  kcal_per_100g numeric not null check (kcal_per_100g >= 0 and kcal_per_100g <= 900),

  protein_g     numeric,
  carbs_g       numeric,
  fat_g         numeric,
  fiber_g       numeric,
  sugar_g       numeric,
  sodium_mg     numeric,

  -- 'usda_fdc' · 'moh_il' · 'manufacturer_label' · 'manual'
  source        text not null,

  -- מזהה שאפשר לחזור אליו: fdcId, מספר פריט במאגר משרד הבריאות,
  -- או ברקוד/קישור לתווית יצרן.
  source_ref    text not null,

  -- 'Foundation' / 'SR Legacy' / 'Branded' ב-FDC. איכות שונה מאוד.
  source_detail text,
  retrieved_at  timestamptz not null default now(),

  -- שמות שהלקוח עשוי לכתוב בוואטסאפ. "אכלתי 200 גרם חזה" צריך למצוא
  -- את חזה העוף. עבודת תרגום, ולכן מותר שמודל ייצר אותה — היא לא מספר.
  aliases_he    jsonb,

  -- מנות נפוצות עם משקל בגרמים: [{"name_he":"כף","grams":15}].
  -- ⚠️ נטען מ-foodPortions של FDC כשקיים. משקל שלא הגיע ממקור לא נכנס:
  -- ניחוש של משקל מנה הוא ניחוש של קלוריות.
  common_servings jsonb,

  -- טקסט חופשי שהיועצת יכולה לצטט: זן, בישול, חלק אכיל.
  note_he       text,

  created_at    timestamptz not null default now(),

  -- מזון אחד לכל מקור. טעינה חוזרת מעדכנת, לא מכפילה.
  unique (source, source_ref, state)
);

create index if not exists foods_name_he_idx  on public.foods (name_he);
create index if not exists foods_category_idx on public.foods (category);

-- ingredient_foods — מה שמחבר "עגבניות בשלות" מתוך מתכון לשורה במאגר.
--
-- ההתאמה בין שם בעברית לרשומה ב-FDC נעשית על ידי אדם או מודל, והיא עלולה
-- להיות שגויה. לכן היא יושבת בטבלה נפרדת עם רמת ביטחון — ולא מודבקת
-- לתוך `foods` כאילו היא חלק מהמדידה.
create table if not exists public.ingredient_foods (
  ingredient_he text primary key,
  food_id       uuid references public.foods(id) on delete set null,

  -- 'exact' — אותו מזון · 'approximate' — קרוב · 'unmapped' — לא נמצא
  confidence    text not null default 'approximate',

  -- כמה גרם ב"יחידה אחת" של המרכיב הזה. null = לא ידוע, ואז אי אפשר
  -- להמיר "5 בינוניות" לגרמים, ולא מנחשים.
  grams_per_unit numeric,
  unit_he        text,

  mapped_at     timestamptz not null default now(),
  mapped_by     text
);

alter table public.foods            enable row level security;
alter table public.ingredient_foods enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 008_rename_chef_to_yoni.sql
-- ─────────────────────────────────────────────────────────────
-- שינוי שם הפרסונה: 'chef' → 'yoni'.
--
-- אותה תבנית בדיוק כמו migrations/003 (nuri → adi): הערך ב-active_bot הוא
-- מזהה פרסונה שהקוד מתייחס אליו, ולכן הוא משתנה כאן. שם הקובץ
-- chef-bot-prompt.md נשאר — לנתיב קובץ אין משמעות בזמן ריצה כמו שיש למפתח,
-- ושינוי שלו הוא רעש בלי תועלת.
--
-- utils/database.js ממפה 'chef' → 'yoni' בקריאה, ונופל חזרה ל-'chef' בכתיבה
-- אם האילוץ הישן עדיין בתוקף. כלומר הקוד והמיגרציה לא חייבים לעלות יחד,
-- ושום שיחה לא נשברת בין הפריסות.
--
-- נתיב חזרה:
--   alter table whapi_conversations drop constraint if exists whapi_conversations_active_bot_check;
--   update whapi_conversations set active_bot = 'chef' where active_bot = 'yoni';
--   alter table whapi_conversations
--     add constraint whapi_conversations_active_bot_check check (active_bot in ('adi', 'chef'));

alter table whapi_conversations
  drop constraint if exists whapi_conversations_active_bot_check;

update whapi_conversations set active_bot = 'yoni' where active_bot = 'chef';

alter table whapi_conversations
  add constraint whapi_conversations_active_bot_check
  check (active_bot in ('adi', 'yoni'));

-- ─────────────────────────────────────────────────────────────
-- 009_unify_on_yoni.sql
-- ─────────────────────────────────────────────────────────────
-- איחוד: שף אחד, יוני, בוט בוואטסאפ.
--
-- ADR-007 קבע שהשף הוא אדם, ושלקוח מבקש שייצרו איתו קשר. במקביל נבנה בוט
-- שעונה בצ'אט מיידית. שתי המערכות חיו זו לצד זו, ולקוח ששילם היה נכנס לתור
-- שאיש לא מנהל בזמן שיוני עונה לו תוך שנייה. ההכרעה החדשה: רק יוני.
--
-- מה שנמחק כאן הוא מסלול-האדם בלבד. המנוי עצמו נשאר — הוא פשוט קונה את יוני.
--
-- נתיב חזרה: git מחזיר את routes/chef.js ואת migrations/006, והטבלה נוצרת
-- מחדש משם. שם המסלול חוזר עם:
--   update public.subscriptions   set plan = 'chef' where plan = 'yoni';
--   update public.payment_events  set plan = 'chef' where plan = 'yoni';

-- שם אחד לפרסונה ולמסלול שקונה אותה.
update public.subscriptions  set plan = 'yoni' where plan = 'chef';
update public.payment_events set plan = 'yoni' where plan = 'chef';

-- מסלול-האדם. אין לו יותר endpoint, ואין לו מי שמנהל את התור שהוא יוצר.
drop table if exists public.chef_requests;

-- ─────────────────────────────────────────────────────────────
-- 010_phone_identity.sql
-- ─────────────────────────────────────────────────────────────
-- קישור בין מספר טלפון לחשבון — התנאי לגבייה על יוני.
--
-- הבעיה: וואטסאפ מזהה אנשים לפי מספר טלפון, ומנויים רשומים על חשבון עם
-- אימייל. לא היה ביניהם שום קשר, ולכן השרת לא ידע מי כותב לו — ולא יכול
-- היה לדעת אם שילם.
--
-- 🔴 מספר טלפון הוא לא הוכחת זהות. הוא מספיק כדי להחליט מי מקבל בוט
-- בישול; הוא לא מספיק לשום דבר חמור מזה. אין כאן מפתח לחשבון.
--
-- נתיב חזרה:
--   alter table public.users drop column phone;
--   alter table whapi_conversations drop column user_id;

-- E.164 בלי הפלוס: 972501234567. צורה אחת בלבד, כי השוואה בין
-- "050-123-4567" ל-"+972501234567" היא באג שמחכה לקרות.
alter table public.users
  add column if not exists phone text;

-- ייחודי, אבל רק על מה שקיים: שני חשבונות על אותו מספר הם תמיד תקלה,
-- ורוב החשבונות לא ימסרו מספר בכלל.
create unique index if not exists users_phone_key
  on public.users (phone)
  where phone is not null;

-- מי מדבר איתנו בוואטסאפ, אם ידוע. null = מספר שלא זוהה, וזה מצב
-- לגיטימי: אדם יכול לכתוב לפני שקנה.
alter table whapi_conversations
  add column if not exists user_id uuid references public.users(id) on delete set null;

create index if not exists whapi_conversations_user_idx
  on whapi_conversations (user_id);

-- ─────────────────────────────────────────────────────────────
-- 011_prompt_provenance.sql
-- ─────────────────────────────────────────────────────────────
-- איזו גרסת פרומפט ענתה ללקוח.
--
-- הבוט אומר לאנשים מה לאכול ובאיזה יעד קלורי. ההצדקה לכך היא שאשת מקצוע
-- כתבה ואישרה את הנוסח. ההצדקה הזו שווה משהו רק אם אפשר להראות **איזה**
-- נוסח היה בתוקף כשנאמר מה שנאמר — שיחה משישה חודשים אחורה מול פרומפט
-- שהשתנה מאז היא בדיוק המצב שבו אי אפשר להגן על כלום.
--
-- הערך הוא persona:12 התווים הראשונים של sha256 של קובץ הפרומפט, למשל
-- "adi:dc4acc971f59". מי שמשווה אותו ל-data/clinical-approvals.json יודע
-- מיד אם הגרסה שענתה היא הגרסה שאושרה.
--
-- null מותר: שורות שנכתבו לפני השינוי הזה, ותשובות מערכת שאינן מהמודל.
--
-- נתיב חזרה: alter table whapi_messages drop column prompt_version;

alter table whapi_messages
  add column if not exists prompt_version text;

create index if not exists whapi_messages_prompt_version_idx
  on whapi_messages (prompt_version);

-- ─────────────────────────────────────────────────────────────
-- 012_staff_role.sql
-- ─────────────────────────────────────────────────────────────
-- is_staff — מי מורשה לקרוא הודעות של לקוחות.
--
-- 🔴 התקלה שזה סוגר: `/api/whatsapp/pending` היה מוגן ב-authMiddleware בלבד,
-- ולא קיים בפרויקט שום מודל תפקידים. כלומר **כל מי שנרשם** — וההרשמה
-- פתוחה ולא מאומתת — יכול היה לקרוא את כל ההודעות הנכנסות במלואן, כולל
-- אלה שסומנו `escalated`, שהן בהגדרה הודעות שבהן אדם כתב "אני בהריון",
-- "יש לי סוכרת" או "הפרעת אכילה", עם מספר הטלפון שלו לצידן.
--
-- אימות מול הרשאה: השאלה "מי אתה" נענתה. השאלה "ומה מותר לך" לא נשאלה.
--
-- ברירת המחדל היא false, כלומר אף אחד. הענקה נעשית ידנית ב-SQL בכוונה:
-- אין endpoint שמעניק אותה, כי endpoint כזה הוא עוד משטח התקפה על בדיוק
-- אותו מידע.
--
--   update public.users set is_staff = true where email = 'someone@example.com';
--
-- נתיב חזרה: alter table public.users drop column is_staff;

alter table public.users
  add column if not exists is_staff boolean not null default false;

create index if not exists users_staff_idx
  on public.users (is_staff) where is_staff = true;

-- ─────────────────────────────────────────────────────────────
-- 013_referrals_and_attribution.sql
-- ─────────────────────────────────────────────────────────────
-- תוכנית הפניות (referrals) וייחוס הרשמה (attribution).
--
-- ארבעה דברים:
--   users.referral_code   — קוד קצר לכל משתמש. נוצר בעצלות, בפעם הראשונה
--                           שמישהו מבקש אותו (GET /api/referrals/me).
--   users.attribution     — מאיפה הגיע המשתמש: utm_*, landing_path, referrer.
--                           first-touch, נשמר פעם אחת בהרשמה.
--   referrals             — מי הזמין את מי. שורה אחת לכל מוזמן.
--   referral_rewards      — מה ההפניה הרוויחה (ימי פרימיום, לפי
--                           REFERRAL_REWARDS ב-utils/constants.js). נרשם בלבד —
--                           שום דבר כאן לא נוגע בחיוב.
--
-- הייחודיות נאכפת באילוצים ולא ב-if: שתי הרשמות מקבילות עם אותו קוד
-- לא יכולות לייצר שתי הפניות לאותו מוזמן או שני תגמולים לאותה הפניה.
--
-- נתיב חזרה:
--   drop table public.referral_rewards;
--   drop table public.referrals;
--   alter table public.users drop column referral_code,
--                            drop column attribution,
--                            drop column referred_by;

alter table public.users
  add column if not exists referral_code text,
  add column if not exists attribution   jsonb,
  add column if not exists referred_by   uuid references public.users(id) on delete set null;

-- ייחודי רק על מה שקיים: רוב המשתמשים לא יבקשו קוד לעולם.
create unique index if not exists users_referral_code_key
  on public.users (referral_code)
  where referral_code is not null;

create table if not exists public.referrals (
  id          uuid primary key default gen_random_uuid(),
  referrer_id uuid not null references public.users(id) on delete cascade,
  referee_id  uuid not null references public.users(id) on delete cascade,

  -- הקוד כפי שהיה בזמן ההרשמה, להיסטוריה.
  code        text not null,

  -- 'signed_up' — נרשם. המרה לתשלום נקראת מטבלת subscriptions ולא נשמרת כאן.
  status      text not null default 'signed_up',
  created_at  timestamptz not null default now(),

  -- אדם לא מפנה את עצמו.
  constraint referrals_not_self check (referrer_id <> referee_id)
);

-- מוזמן אחד — מפנה אחד. ההפניה הראשונה מנצחת ולא מוחלפת.
create unique index if not exists referrals_referee_key
  on public.referrals (referee_id);

create index if not exists referrals_referrer_idx
  on public.referrals (referrer_id, created_at desc);

create table if not exists public.referral_rewards (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.users(id) on delete cascade,

  -- תגמול שהורווח נשאר גם אם המוזמן מחק את החשבון.
  referral_id uuid references public.referrals(id) on delete set null,

  -- 'premium_days'
  type        text not null,
  amount      integer not null check (amount >= 0),

  -- 'referee_signup'
  reason      text not null,

  -- 'earned' — נרשם · 'applied' — הוחל על מנוי (בעתיד) · 'revoked'
  status      text not null default 'earned',
  created_at  timestamptz not null default now()
);

-- תגמול אחד לכל הפניה לכל משתמש: handler שרץ פעמיים לא משלם פעמיים.
create unique index if not exists referral_rewards_once_key
  on public.referral_rewards (referral_id, user_id);

create index if not exists referral_rewards_user_idx
  on public.referral_rewards (user_id, created_at desc);

-- 🔴 מי הזמין את מי הוא מידע אישי. RLS מופעל, בלי policies, כמו שאר הטבלאות.
alter table public.referrals        enable row level security;
alter table public.referral_rewards enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 014_marketing_leads.sql
-- ─────────────────────────────────────────────────────────────
-- marketing_leads — מי שהשאיר אימייל בדף הנחיתה.
--
-- שורה אחת לכל כתובת. האימייל נשמר כבר מנורמל (trim + אותיות קטנות) על ידי
-- routes/marketing.js, והאינדקס הייחודי הוא שמכריע אם הגשה חדשה או חוזרת —
-- לא if בקוד. הגשה חוזרת לא דורסת את ה-source/utm_* של הביקור הראשון;
-- היא רק מעדכנת last_submitted_at ו-submissions.
--
-- consent_at: חוק התקשורת, סעיף 30א — דיוור שיווקי דורש הסכמה מפורשת.
-- ה-API מסרב לכל הגשה בלי תיבת הסכמה מסומנת, והזמן נשמר כאן כראיה.
--
-- אלה נתונים אישיים של אנשים שעוד אינם לקוחות: RLS פעיל בלי policies,
-- והגישה היא רק דרך SUPABASE_SERVICE_ROLE_KEY (כמו טבלאות ה-whapi).
-- קריאה דרך ה-API: GET /api/marketing/leads — staff בלבד.
--
-- נתיב חזרה: drop table public.marketing_leads;

create table if not exists public.marketing_leads (
  id                uuid primary key default gen_random_uuid(),
  email             text not null,
  name              text,
  lang              text not null default 'he' check (lang in ('he', 'en')),

  -- ייחוס first-touch: מאיפה הגיע הביקור הראשון.
  source            text,
  utm_source        text,
  utm_medium        text,
  utm_campaign      text,
  utm_term          text,
  utm_content       text,

  consent_at        timestamptz not null,
  submissions       integer not null default 1,
  created_at        timestamptz not null default now(),
  last_submitted_at timestamptz not null default now(),

  -- הקוד שומר באותיות קטנות; האילוץ מוודא שזה נשאר כך גם בהכנסה ידנית.
  constraint marketing_leads_email_normalized check (email = lower(btrim(email)))
);

create unique index if not exists marketing_leads_email_key
  on public.marketing_leads (email);

create index if not exists marketing_leads_created_idx
  on public.marketing_leads (created_at desc);

alter table public.marketing_leads enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 015_onboarding.sql
-- ─────────────────────────────────────────────────────────────
-- אשף הכניסה (onboarding) — מתי המשתמש סיים אותו.
--
-- users.onboarding_completed_at — נכתב פעם אחת, כשהמשתמש מסיים או מדלג על
--                                 האשף (POST /api/onboarding). null = עוד לא.
--
-- כל שאר מה שהאשף אוסף נשמר במקומות הקיימים: users.preferences (מטרה,
-- העדפות תזונה, יעדים יומיים, תזכורות), weight_goals, hydration_logs.
-- משתמשים ותיקים עם העדפות/יעדים/תיעודים נחשבים כמי שסיימו גם בלי העמודה
-- (utils/onboarding.js), כך שאין צורך ב-backfill.
--
-- נתיב חזרה:
--   alter table public.users drop column onboarding_completed_at;

alter table public.users
  add column if not exists onboarding_completed_at timestamptz;

-- ─────────────────────────────────────────────────────────────
-- 016_share_cards.sql
-- ─────────────────────────────────────────────────────────────
-- share_cards — קישורי "שתפו את השבוע שלי" (routes/share.js).
--
-- כל שורה היא תמונת מצב (snapshot) קפואה של שבוע, שעברה סינון פרטיות לפני
-- שנשמרה: שם פרטי בלבד (ורק אם הבעלים השאיר אותו), בלי אימייל, בלי מזהה
-- משתמש, ובלי מספרי משקל אלא אם הבעלים סימן זאת — וגם אז רק השינוי השבועי.
-- ה-snapshot נבנה בשרת מהנתונים, לעולם לא ממספרים שהלקוח שולח.
--
-- הטוקן עצמו לא נשמר: רק SHA-256 שלו (token_hash). דליפה של הטבלה לא
-- מחלקת קישורים עובדים. 192 ביט אקראיים — ניחוש אינו מעשי.
--
-- תוקף: expires_at (30 יום). ביטול על ידי הבעלים: revoked_at (והתמונה נמחקת).
--
-- image_png — רינדור PNG של הכרטיס שהדפדפן של הבעלים מעלה, כדי ש-og:image
-- יהיה PNG (וואטסאפ/פייסבוק מתעלמים מ-SVG). base64 ב-text ולא bytea: כך
-- supabase-js מחזיר אותו בלי המרת hex. מוגבל ל-800KB ולמידות 1200×630 בקוד.
--
-- נתיב חזרה:
--   drop table public.share_cards;

create table if not exists public.share_cards (
  id          uuid primary key default gen_random_uuid(),
  token_hash  text not null,
  user_id     uuid not null references public.users(id) on delete cascade,
  snapshot    jsonb not null,
  ref_code    text,
  lang        text not null default 'he' check (lang in ('he', 'en')),
  image_png   text,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null,
  revoked_at  timestamptz
);

create unique index if not exists share_cards_token_hash_key
  on public.share_cards (token_hash);

-- מגבלת יצירה יומית לכל משתמש (countCreatedSince).
create index if not exists share_cards_user_created_idx
  on public.share_cards (user_id, created_at desc);

-- 🔴 RLS מופעל בלי policies, כמו שאר הטבלאות; הגישה דרך השרת בלבד.
alter table public.share_cards enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 018_lifecycle_messaging.sql
-- ─────────────────────────────────────────────────────────────
-- דיוור מחזור-חיים (lifecycle): טיפוח לידים, onboarding, רצף בסיכון, win-back.
--
-- שלושה דברים:
--   notification_preferences — העדפות דיוור לכל משתמש: מיילים של השירות,
--                              דיוור שיווקי (הסכמה מפורשת, חוק התקשורת 30א),
--                              וואטסאפ (opt-in בלבד), שפה ואזור זמן.
--   lifecycle_sends          — יומן שליחה. שורה אחת לכל (נמען, קמפיין, תקופה).
--                              האינדקס הייחודי הוא מה שמונע שליחה כפולה —
--                              גם בין הפעלות מחדש של השרת וגם כששתי ריצות
--                              של ה-cron חופפות: השורה נתפסת (status='pending')
--                              לפני השליחה, ורק מי שהכניס אותה שולח.
--   marketing_leads.unsubscribed_at — ליד שביקש הסרה לא מקבל עוד דיוור.
--
-- recipient_id הוא users.id או marketing_leads.id לפי recipient_type, ולכן
-- אין עליו foreign key. מחיקת משתמש/ליד מוחקת גם את השורות שלו בקוד
-- (utils/database.js), ומחיקת ליד לפי בקשה (POST /api/marketing/leads/forget)
-- מוחקת את שתיהן.
--
-- נתונים אישיים: RLS פעיל בלי policies, גישה רק דרך SUPABASE_SERVICE_ROLE_KEY.
--
-- נתיב חזרה:
--   drop table public.lifecycle_sends;
--   drop table public.notification_preferences;
--   alter table public.marketing_leads drop column unsubscribed_at;

create table if not exists public.notification_preferences (
  user_id              uuid primary key references public.users(id) on delete cascade,
  -- מיילים של השירות (ברוכים הבאים, טיפים, תזכורת רצף). ברירת מחדל: כן.
  email_lifecycle      boolean not null default true,
  -- דיוור שיווקי (win-back). ברירת מחדל: לא — רק בהסכמה מפורשת.
  marketing_email      boolean not null default false,
  marketing_consent_at timestamptz,
  -- וואטסאפ: opt-in בלבד.
  whatsapp             boolean not null default false,
  whatsapp_consent_at  timestamptz,
  lang                 text check (lang in ('he', 'en')),
  timezone             text,
  unsubscribed_at      timestamptz,
  updated_at           timestamptz not null default now()
);

create table if not exists public.lifecycle_sends (
  id             uuid primary key default gen_random_uuid(),
  recipient_type text not null check (recipient_type in ('user', 'lead')),
  recipient_id   uuid not null,
  campaign       text not null,
  step           text not null,
  -- מפתח התקופה: שם השלב לשלבים חד-פעמיים ("day2"), תאריך מקומי לתזכורת
  -- רצף ("2026-09-27"), או "d7:<תאריך פעילות אחרון>" ל-win-back.
  period_key     text not null,
  channel        text not null check (channel in ('email', 'whatsapp')),
  status         text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  error          text,
  created_at     timestamptz not null default now(),
  sent_at        timestamptz,
  opened_at      timestamptz,
  converted_at   timestamptz
);

create unique index if not exists lifecycle_sends_once_key
  on public.lifecycle_sends (recipient_type, recipient_id, campaign, period_key);

create index if not exists lifecycle_sends_recipient_idx
  on public.lifecycle_sends (recipient_type, recipient_id, created_at desc);

create index if not exists lifecycle_sends_campaign_idx
  on public.lifecycle_sends (campaign, status);

alter table public.marketing_leads
  add column if not exists unsubscribed_at timestamptz;

alter table public.notification_preferences enable row level security;
alter table public.lifecycle_sends          enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 019_analytics_indexes.sql
-- ─────────────────────────────────────────────────────────────
-- אינדקסים ללוח הבקרה השיווקי (routes/analytics.js, staff בלבד).
--
-- כל endpoint שם מתחיל ב"מי נרשם / מי הופנה / מי השאיר אימייל בטווח
-- התאריכים", כלומר טווח על created_at. ל-users ול-referrals אין אינדקס כזה
-- (ל-marketing_leads יש, ממיגרציה 014), ובלעדיו כל טעינה של הדשבורד היא
-- סריקה מלאה של טבלת המשתמשים.
--
-- שאר הקריאות כבר מכוסות: לוגים לפי (user_id, date/created_at) ממיגרציה 001,
-- subscriptions לפי user_id ממיגרציה 005, referral_rewards לפי
-- (referral_id, user_id) ממיגרציה 013.
--
-- אין כאן שינוי נתונים ואין עמודות חדשות. בטוח להרצה חוזרת.
--
-- נתיב חזרה:
--   drop index if exists public.users_created_at_idx;
--   drop index if exists public.referrals_created_at_idx;

create index if not exists users_created_at_idx
  on public.users (created_at);

create index if not exists referrals_created_at_idx
  on public.referrals (created_at);

-- ─────────────────────────────────────────────────────────────
-- 020_web_push.sql
-- ─────────────────────────────────────────────────────────────
-- Web Push: מנויי דפדפן להתראות, והגדרות תזכורות למשתמש.
--
-- שתי טבלאות:
--   push_subscriptions      — דפדפן אחד במכשיר אחד. ה-endpoint הוא הזהות שלו
--                             וייחודי: דפדפן שעבר לחשבון אחר עובר איתו, ולא
--                             ממשיך לקבל התראות של החשבון הקודם.
--                             מנוי שה-push service מחזיר עליו 404/410 נמחק
--                             (utils/push.js).
--   push_reminder_settings  — שורה אחת למשתמש: אילו תזכורות הוא רוצה (מים,
--                             רישום ארוחה, רצף בסיכון), שעות שקטות ואזור זמן.
--                             state — מתי כל תזכורת נשלחה לאחרונה; רק
--                             ה-scheduler כותב אותו.
--
-- מספרים 013–019 שמורים לעבודה אחרת; זו 020.
--
-- 🔴 p256dh/auth מאפשרים לשלוח התראות לדפדפן הזה. RLS מופעל בלי policies,
-- והגישה רק דרך SUPABASE_SERVICE_ROLE_KEY (כמו marketing_leads וטבלאות whapi).
--
-- נתיב חזרה:
--   drop table public.push_reminder_settings;
--   drop table public.push_subscriptions;

create table if not exists public.push_subscriptions (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references public.users(id) on delete cascade,
  endpoint        text not null,
  p256dh          text not null,
  auth            text not null,
  user_agent      text,

  -- כשלונות רצופים שאינם 404/410 (למשל 5xx זמני). מתאפס בהצלחה.
  failure_count   integer not null default 0,
  last_success_at timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists push_subscriptions_endpoint_key
  on public.push_subscriptions (endpoint);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);

create table if not exists public.push_reminder_settings (
  user_id    uuid primary key references public.users(id) on delete cascade,
  enabled    boolean not null default false,

  -- IANA, למשל Asia/Jerusalem. "עכשיו" של התזכורות נמדד בו.
  tz         text not null default 'Asia/Jerusalem',
  lang       text not null default 'he' check (lang in ('he', 'en')),

  -- { quietHours: {start,end}, water: {enabled,intervalMinutes,start,end},
  --   meal: {enabled,time}, streak: {enabled,time} } — מאומת ב-routes/push.js.
  settings   jsonb not null default '{}'::jsonb,
  state      jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ה-scheduler קורא רק את מי שהפעיל תזכורות.
create index if not exists push_reminder_settings_enabled_idx
  on public.push_reminder_settings (enabled)
  where enabled;

alter table public.push_subscriptions     enable row level security;
alter table public.push_reminder_settings enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 021_scheduler_indexes.sql
-- ─────────────────────────────────────────────────────────────
-- אינדקסים לקריאות המרוכזות של ה-schedulers.
--
-- ריצת ה-lifecycle השעתית (utils/lifecycle-runner.js) ותזכורות ה-push כל
-- חמש דקות (utils/push.js) קוראות עכשיו עמוד של 200 משתמשים בכל פעם:
--   select ... from <logs> where user_id in (...) order by user_id, created_at desc, id
-- ולא שאילתה לכל משתמש. כדי שהסדר יגיע ישר מהאינדקס (בלי מיון מחדש לכל
-- עמוד של range()) צריך (user_id, created_at desc). ל-food_logs,
-- weight_logs, weight_goals ו-surveys יש כבר אינדקס כזה ממיגרציה 001;
-- ל-hydration_logs ול-sleep_logs יש רק (user_id, date desc).
--
-- תזכורות ה-push עוברות על מי שהפעיל תזכורות בדפים לפי user_id
-- (where enabled order by user_id, keyset). האינדקס החלקי ממיגרציה 020 הוא
-- על (enabled) בלבד ולא נותן את הסדר; זה החלקי על user_id כן.
--
-- שאר הקריאות כבר מכוסות: lifecycle_sends לפי (recipient_type,
-- recipient_id, created_at desc) ממיגרציה 018, push_subscriptions לפי user_id
-- ממיגרציה 020, notification_preferences/users/marketing_leads לפי המפתח
-- הראשי.
--
-- תלויה ב-020 (push_reminder_settings) — להריץ אחריה.
-- אין כאן שינוי נתונים ואין עמודות חדשות. בטוח להרצה חוזרת.
-- בטבלאות לוגים גדולות אפשר להריץ כל שורה בנפרד עם
-- "create index concurrently if not exists ..." (מחוץ לטרנזקציה) כדי לא
-- לחסום כתיבות בזמן הבנייה.
--
-- נתיב חזרה:
--   drop index if exists public.hydration_logs_user_created_idx;
--   drop index if exists public.sleep_logs_user_created_idx;
--   drop index if exists public.push_reminder_settings_enabled_user_idx;

create index if not exists hydration_logs_user_created_idx
  on public.hydration_logs (user_id, created_at desc);

create index if not exists sleep_logs_user_created_idx
  on public.sleep_logs (user_id, created_at desc);

create index if not exists push_reminder_settings_enabled_user_idx
  on public.push_reminder_settings (user_id)
  where enabled;

-- ─────────────────────────────────────────────────────────────
-- 022_meal_planner_weeks.sql
-- ─────────────────────────────────────────────────────────────
-- meal_planner_weeks — מתכנן הארוחות השבועי (7 ימים × בוקר/צהריים/ערב/נשנוש)
-- ורשימת הקניות שנגזרת ממנו.
--
-- שורה אחת למשתמש לכל שבוע (week_start = יום ראשון של השבוע). התוכנית
-- עצמה נשמרת כ-jsonb: לכל ארוחה — מזהה התבנית, האם היא נעולה, והכמויות
-- בגרמים של כל רכיב. הערכים התזונתיים לא נשמרים כאן בכוונה: הם מחושבים
-- בכל קריאה מ-data/food-database.json ו-data/foods-usda.json
-- (utils/meal-planner.js), כך שתיקון ערך במאגר מתקן גם תוכניות קיימות.
--
-- checked_items — מפתחות הפריטים שסומנו ברשימת הקניות. הלקוח שולח את
-- הרשימה המלאה (last write wins), כך שאין read-modify-write בשרת.
--
-- זה לא מחליף את meal_plans (004): שם מתכון אחד לכל משבצת, כאן ארוחה
-- מורכבת עם כמויות שמכוונות ליעדים האישיים.
--
-- 🔴 תוכנית תזונה אישית (כולל אלרגיות שנגזרות ממנה) היא מידע בריאותי.
-- RLS מופעל בלי policies; הגישה רק דרך SUPABASE_SERVICE_ROLE_KEY — ה-backend
-- הוא השוער, כמו push_subscriptions.
--
-- נתיב חזרה:
--   drop table public.meal_planner_weeks;

create table if not exists public.meal_planner_weeks (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references public.users(id) on delete cascade,
  week_start    date not null,

  -- ה-seed שממנו נבנתה התוכנית; החלפה/יצירה מחדש מקדמים אותו, כך
  -- שאותה פעולה על אותה תוכנית תמיד נותנת אותה תוצאה.
  seed          bigint not null default 1,

  -- { version, targets, days: [{ date, meals: [{ slot, templateId, locked,
  --   items: [{ ing, grams }] }] }] } — מאומת ב-routes/meal-planner.js.
  plan          jsonb not null,
  checked_items text[] not null default '{}',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  -- שבוע אחד לכל משתמש. גם האינדקס של הקריאות (user_id, week_start).
  constraint meal_planner_weeks_user_week_key unique (user_id, week_start)
);

alter table public.meal_planner_weeks enable row level security;

-- ─────────────────────────────────────────────────────────────
-- 025_monetization.sql
-- ─────────────────────────────────────────────────────────────
-- יסודות המונטיזציה: קטלוג מסלולים, הרשאות, תגמולי הפניה שמוחלים בפועל.
--
-- כבוי כברירת מחדל: שום דבר כאן לא גובה כסף ולא נועל פיצ'ר. החיוב נפתח רק עם
-- CHECKOUT_ENABLED=true + CANCELLATION_POLICY_URL, והנעילה רק עם
-- ENTITLEMENTS_ENFORCED=true (ראו utils/checkout.js, utils/entitlements.js).
--
--   users.premium_until            — עד מתי יש למשתמש פרימיום מימי הפניה.
--                                    ימי פרימיום לא נכתבים ל-subscriptions: שם
--                                    רק מה ששולם, וזה מה ששלב "משלמים"
--                                    במשפך סופר.
--   referral_rewards.applied_at    — מתי התגמול הוחל על premium_until. השורה
--                                    עוברת earned → applied בעדכון מותנה, כך
--                                    שתגמול לא מוחל פעמיים.
--   whatsapp_chef_trials           — כמה הודעות חינם עם יוני נוצלו, לפי מספר
--                                    וואטסאפ (אנשים כותבים לפני שיש להם חשבון).
--   subscriptions (status, ends_at) — אינדקס לקריאות "מסתיים בקרוב" (תזכורת
--                                    חידוש, מסך בריאות המערכת).
--
-- תלויה ב-005 (subscriptions) וב-013 (referral_rewards). בטוחה להרצה חוזרת.
--
-- נתיב חזרה:
--   drop index if exists public.subscriptions_active_ends_idx;
--   drop table if exists public.whatsapp_chef_trials;
--   alter table public.referral_rewards drop column if exists applied_at;
--   alter table public.users drop column if exists premium_until;

alter table public.users
  add column if not exists premium_until timestamptz;

alter table public.referral_rewards
  add column if not exists applied_at timestamptz;

create table if not exists public.whatsapp_chef_trials (
  -- כפי שמגיע מ-WHAPI (chat_id), כמו whapi_conversations.phone.
  phone      text primary key,
  used       integer not null default 0 check (used >= 0),
  updated_at timestamptz not null default now()
);

create index if not exists subscriptions_active_ends_idx
  on public.subscriptions (ends_at)
  where status = 'active';

-- 🔴 מספר טלפון הוא מידע אישי. RLS מופעל, בלי policies — גישה רק דרך
-- SUPABASE_SERVICE_ROLE_KEY, כמו whapi_conversations.
alter table public.whatsapp_chef_trials enable row level security;
